# Generated by Django 5.1.7 on 2025-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('Заказ принят', 'Заказ принят'), ('В пути', 'В пути'), ('Готов к выдаче', 'Готов к выдаче'), ('Товар передан клиенту', 'Товар передан клиенту')], default='Заказ принят', max_length=255)),
                ('payment_status', models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Наличными', 'Наличными'), ('Оплачен картой', 'Оплачен картой')], default='Не оплачен', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
