# Generated by Django 5.1.7 on 2025-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
