# Generated by Django 5.1.7 on 2025-06-12 13:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price_seller',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена поставщика'),
            preserve_default=False,
        ),
    ]
