# Generated by Django 5.1.7 on 2025-06-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_category_alter_stock_options_stock_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fixed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Получено изначально'),
        ),
    ]
