# Generated by Django 5.1.7 on 2025-06-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_stock_fixed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fixed_quantity',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Получено изначально'),
        ),
    ]
