# Generated by Django 5.1.7 on 2025-06-17 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_returnitem_sale_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'ordering': ['-opened_at'],
            },
        ),
    ]
