# Generated by Django 5.1.7 on 2025-06-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_cashsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashSession',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='sale_item',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fixed_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_seller',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('reserved', 'В резерве'), ('sold_out', 'Продано'), ('ordered', 'Заказан')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='SaleHistory',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
