# Generated by Django 5.1.7 on 2025-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_delete_cashsession_remove_stock_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('Приехал', 'В наличии'), ('На складе', 'В резерве'), ('Передан', 'Продано')], default='in_stock', max_length=20),
        ),
    ]
