# Generated by Django 5.1.7 on 2025-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_stock_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('Приехал', 'Приехал'), ('На складе', 'На складе'), ('Передан', 'Передан')], default='in_stock', max_length=20),
        ),
    ]
