# Generated by Django 5.1.7 on 2025-06-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
