# Generated by Django 5.1.7 on 2025-08-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
