# Generated by Django 5.1.7 on 2025-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='client_id',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('На складе Китая', 'На складе Китая'), ('В пути', 'В пути'), ('Приехал', 'Приехал'), ('На складе', 'На складе'), ('Передан', 'Передан')], default='На складе Китая', max_length=20),
        ),
    ]
