# Generated by Django 5.1.7 on 2025-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_stock_client_id_alter_stock_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
    ]
