# Generated by Django 5.1.7 on 2025-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_stock_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='weight',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
