# Generated by Django 5.1.7 on 2025-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_stock_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('Заказ принят', 'Заказ принят'), ('В пути', 'В пути'), ('В Кыргызстане', 'В Кыргызстане'), ('Товар получен', 'Товар получен')], default='Заказ принят', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
