# Generated by Django 5.1.7 on 2025-08-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_remove_stock_quantity_alter_stock_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
