# Generated by Django 5.1.7 on 2025-08-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_remove_stock_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
