# Generated by Django 5.1.7 on 2025-08-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_remove_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='payment_status',
            field=models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Оплачен наличными', 'Оплачен наличными'), ('Оплачен картой', 'Оплачен картой')], default='Не оплачен', max_length=20),
        ),
    ]
