# Generated by Django 5.1.7 on 2025-08-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_stock_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='order_status',
            field=models.CharField(choices=[('Заказ принят', 'Заказ принят'), ('В пути', 'В пути'), ('Готов к выдаче', 'Готов к выдаче'), ('Товар передан клиенту', 'Товар передан клиенту')], default='Заказ принят', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='payment_status',
            field=models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Наличными', 'Наличными'), ('Оплачен картой', 'Оплачен картой')], default='Не оплачен', max_length=255),
        ),
    ]
