# Generated by Django 5.1.7 on 2025-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('pickUpPoint', models.CharField(choices=[('Кара-Балта', 'Кара-Балта'), ('Сокулук', 'Сокулук'), ('Беловодское', 'Беловодское')], max_length=100)),
                ('warehouse', models.TextField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
